[project]
name = "end-to-end-ml-dl-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cryptography>=45.0.7",
    "databricks-sql-connector>=4.1.2",
    "dbt-core>=1.10.10",
    "dbt-databricks>=1.10.9"
]
