dbt_databrick:
  outputs:
    dev:
      catalog: olist_dataset
      host: dbc-214ffec4-c1f2.cloud.databricks.com
      http_path: /sql/1.0/warehouses/8753fa7395d762fe
      schema: dbt_schema
      threads: 1
      type: databricks
  target: dev
